const cp = require('child_process')
//cp.execSync('calc')
//cp.execSync('start chrome https://www.youtube.com/watch?v=G8a1lz10H-Q')
//console.log(cp.execSync('node demo.js'))
console.log('output '+cp.execSync('node demo.js'))